1286827 + 0 in total (QC-passed reads + QC-failed reads)
595661 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
1281533 + 0 mapped (99.59%:-nan%)
691166 + 0 paired in sequencing
345583 + 0 read1
345583 + 0 read2
605666 + 0 properly paired (87.63%:-nan%)
684846 + 0 with itself and mate mapped
1026 + 0 singletons (0.15%:-nan%)
1970 + 0 with mate mapped to a different chr
553 + 0 with mate mapped to a different chr (mapQ>=5)
