440280 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
440280 + 0 mapped (100.00%:N/A)
440280 + 0 paired in sequencing
220140 + 0 read1
220140 + 0 read2
440280 + 0 properly paired (100.00%:N/A)
440280 + 0 with itself and mate mapped
0 + 0 singletons (0.00%:N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
